networks:
  network:
    driver: bridge
    internal: false

services:
  valkey:
    image: valkey/valkey:8.1.2-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      - network
    volumes:
      - valkey_data:/data
    secrets:
      - valkey_config
    command: valkey-server /run/secrets/valkey_config

  backend:
    build:
      context: . # Allow the backend build steps access the Frontend directory
      dockerfile: ./backend/Dockerfile
    container_name: backend
    restart: unless-stopped
    networks:
      - network
    hostname: backend
    environment:
      - ROLE=Backend
      - COLOR=blue
      - PORT=8080
      - CACHE_PORT=6379
      - CACHE_CONTAINER_NAME=valkey
      - CACHE_ID_LENGTH=15
      - CACHE_VERSION=1
      - SERVICE_ID_LENGTH=15
      - DEV_MODE=false
    ports:
      - "8080:8080"
    secrets:
      - source: valkey_backend
        target: valkey.json
    volumes:
      - backend-data:/home/appuser/CheckBag

volumes:
  valkey_data:
    name: valkey-data
  backend-data:
    name: backend-data

secrets:
  valkey_backend:
    file: ./.secrets/valkey.json
  valkey_config:
    file: ./.secrets/valkey.conf
