networks:
  network:
    driver: bridge
    internal: false

services:
  valkey:
    image: valkey/valkey:8.1.2-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      - network
    volumes:
      - valkey_data:/data
    command: valkey-server --requirepass ${CACHE_PASSWORD}

  backend:
    build:
      context: . # Allow the backend build steps access the Frontend directory
      dockerfile: ./backend/Dockerfile
    container_name: backend
    restart: unless-stopped
    networks:
      - network
    hostname: backend
    environment:
      - ROLE=Backend
      - COLOR=blue
      - PORT=8080
      - CACHE_ID_LENGTH=15
      - CACHE_VERSION=1
      - SERVICE_ID_LENGTH=15
      - DEV_MODE=false
    env_file:
      - .env
    ports:
      - "${WEB_UI_PORT}:8080"
    volumes:
      - backend-data:/home/appuser/CheckBag

volumes:
  valkey_data:
    name: valkey-data
  backend-data:
    name: backend-data
