networks:
  network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: unless-stopped
    networks:
      - network
    hostname: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  valkey:
    image: valkey/valkey:8.1.2-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      - network
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --requirepass ${CACHE_PASSWORD}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    networks:
      - network
    hostname: backend
    environment:
      - ROLE=Backend
      - COLOR=blue
      - PORT=8080
      - CACHE_ID_LENGTH=15
      - SERVICE_ID_LENGTH=15
      - DEV_MODE=true
    env_file:
      - .env
    ports:
      - "${WEB_UI_PORT}:8080"
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - backend-data:/home/appuser/CheckBag

volumes:
  valkey_data:
    name: valkey-data
  backend-data:
    name: backend-data
