networks:
  network:
    driver: bridge
    internal: false

services:
  nginx:
    build:
      context: . # Allow NGINX to access the Frontend directory
      dockerfile: ./router/Dockerfile
    container_name: nginx
    restart: unless-stopped
    networks:
      - network
    ports:
      - "8080:80"

  valkey:
    image: valkey/valkey:8.1.2-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      - network
    volumes:
      - valkey_data:/data
    secrets:
      - valkey_config
    command: valkey-server /run/secrets/valkey_config

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    networks:
      - network
    hostname: backend
    environment:
      - ROLE=Backend
      - COLOR=blue
      - PORT=9001
      - CACHE_PORT=6379
      - CACHE_CONTAINER_NAME=valkey
      - CACHE_ID_LENGTH=15
      - SERVICE_ID_LENGTH=15
      - DEV_MODE=false
    secrets:
      - source: valkey_backend
        target: valkey.json
    volumes:
      - ./backend:/app
      - backend-data:/home/appuser/CheckBag

volumes:
  valkey_data:
    name: valkey-data
  backend-data:
    name: backend-data

secrets:
  valkey_backend:
    file: ./.secrets/valkey.json
  valkey_config:
    file: ./.secrets/valkey.conf
